<?php
declare(strict_types=1); ini_set('display_errors', '1');
error_reporting(E_ALL); require_once __DIR__ . '/phpmailer/Exception.php';
require_once __DIR__ . '/phpmailer/PHPMailer.php';
require_once __DIR__ . '/phpmailer/SMTP.php'; use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception as MailException; function out(string $s): void { echo "<pre style='white-space:pre-wrap;font-family:Arial,sans-serif;'>" . htmlspecialchars($s) . "</pre>";
} try { $smtp = require __DIR__ . '/_smtp_config.php'; if (!is_array($smtp)) { throw new Exception('SMTP-Konfiguration ist ungültig (kein Array). Prüfe _smtp_config.php (muss return [..] haben).'); } $need = ['host','port','encryption','username','password']; foreach ($need as $k) { if (!isset($smtp[$k]) || trim((string)$smtp[$k]) === '') { throw new Exception('SMTP-Konfiguration unvollständig: ' . $k . ' fehlt.'); } } $from = trim((string)$smtp['username']); if (!filter_var($from, FILTER_VALIDATE_EMAIL)) { throw new Exception('SMTP username ist keine gültige E-Mail-Adresse: ' . $from); } // ✅ Schicke Testmail an dich selbst: $to = $from; $mail = new PHPMailer(true); $mail->CharSet = 'UTF-8'; $mail->isSMTP(); $mail->Host = (string)$smtp['host']; $mail->SMTPAuth = true; $mail->Username = (string)$smtp['username']; $mail->Password = (string)$smtp['password']; $mail->Port = (int)$smtp['port']; $mail->SMTPSecure = (string)$smtp['encryption']; // tls $mail->SMTPAutoTLS = true; // 🔎 Debug output (zeige, was passiert) $mail->SMTPDebug = 2; // 0 = aus, 2 = detailliert $mail->Debugoutput = function ($str, $level) { echo "<div style='font-family:monospace;white-space:pre-wrap;'>" . htmlspecialchars($str) . "</div>"; }; $mail->setFrom($from, 'KündigungExpress SMTP Test'); $mail->Sender = $from; $mail->addAddress($to); $mail->Subject = 'SMTP Test – KündigungExpress (' . date('d.m.Y H:i:s') . ')'; $mail->Body = "Hallo!\n\nWenn du diese E-Mail bekommst, funktioniert SMTP über IONOS.\n\nViele Grüße\nKündigungExpress"; $mail->send(); out("✅ OK: Testmail wurde gesendet an: " . $to); } catch (MailException $e) { out("❌ PHPMailer Fehler:\n" . $e->getMessage());
} catch (Exception $e) { out("❌ Fehler:\n" . $e->getMessage());
}
